### PR TITLE
Add support for Modalova

### PR DESCRIPTION
**Pull request by gabriel-kaam**
Adds support for the modalova website (https://www.modalova.fr/)

### CODE REVIEW

**Comment by gabriel-kaam** [comment]
@tareq1988 any news on this ?

**Comment by tareq1988** [comment]
@gabriel-kaam is this https://www.modalova.fr/ site a system like Google Ads or Facebook Ads? Seems like it's e-commerce website. So I don't understand the need for this PR.

**Comment by gabriel-kaam** [comment]
Hi @tareq1988 , it is more a marketplace like eBay or Estsy

**Comment by tareq1988** [comment]
I don't feel this is the right feature addition for this plugin, so it won't be merged. 

Thank you for your contribution though, any future contribution will be appreciated 🙏

**Pull request closed without merging**
